package dev.aj.groovyjava.warehouse

import dev.aj.groovyjava.db.DBConnectionProperties
import groovy.sql.Sql

def credentials = DBConnectionProperties.getConnectionCredentials()

def sql = Sql.newInstance(credentials.url.concat('?currentSchema=warehouse'), credentials.userName, credentials.password, credentials.driverClassName)
println('Connected')

sql.execute("""

	Drop TABLE if exists users cascade;
	Drop TABLE if exists products cascade;
	Drop TABLE if exists orders;

	create table users (
	    id SERIAL PRIMARY KEY,
	    first_name varchar(50),
	    last_name varchar(50)
	);

	CREATE TABLE products (
	  	id SERIAL PRIMARY KEY,
  		name VARCHAR(100),
  		department VARCHAR(75),
  		price INTEGER,
  		weight INTEGER
	);
	CREATE TABLE orders (
  		id SERIAL PRIMARY KEY,
  		user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  		product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,
  		paid BOOLEAN
	);
""")

def usersData = [
		[first_name: 'Iva', last_name: 'Lindgren'],
		[first_name: 'Jannie', last_name: 'Boehm'],
		[first_name: 'Neal', last_name: 'Wehner'],
		[first_name: 'Mikayla', last_name: 'Casper'],
		[first_name: 'Patience', last_name: 'Stracke'],
		[first_name: 'Josianne', last_name: 'Gerhold'],
		[first_name: 'Kailee', last_name: 'Jacobson'],
		[first_name: 'Marlen', last_name: 'Hickle'],
		[first_name: 'Pansy', last_name: 'Daugherty'],
		[first_name: 'Vinnie', last_name: 'Feest'],
		[first_name: 'Cierra', last_name: 'Johns'],
		[first_name: 'Violette', last_name: 'Heathcote'],
		[first_name: 'Stan', last_name: 'Rath'],
		[first_name: 'Neha', last_name: 'Hyatt'],
		[first_name: 'Kaylah', last_name: 'Gleason'],
		[first_name: 'Jacky', last_name: 'Hegmann'],
		[first_name: 'Duane', last_name: 'Lockman'],
		[first_name: 'Sonya', last_name: 'Marquardt'],
		[first_name: 'Brenden', last_name: 'Streich'],
		[first_name: 'Laurianne', last_name: 'Douglas'],
		[first_name: 'Orlando', last_name: 'Kerluke'],
		[first_name: 'Irma', last_name: 'Wintheiser'],
		[first_name: 'Cletus', last_name: 'Schultz'],
		[first_name: 'Jermaine', last_name: 'Langosh'],
		[first_name: 'Alexanne', last_name: 'Dickens'],
		[first_name: 'Garret', last_name: 'Williamson'],
		[first_name: 'Max', last_name: 'Goodwin'],
		[first_name: 'Tad', last_name: 'Wilderman'],
		[first_name: 'Lindsay', last_name: 'Yost'],
		[first_name: 'Elliot', last_name: 'Oberbrunner'],
		[first_name: 'Brendan', last_name: 'Thompson'],
		[first_name: 'Brennan', last_name: 'Auer'],
		[first_name: 'Luigi', last_name: 'Johnston'],
		[first_name: 'Garth', last_name: 'McLaughlin'],
		[first_name: 'Ressie', last_name: 'Nikolaus'],
		[first_name: 'Ruby', last_name: 'Turner'],
		[first_name: 'Caden', last_name: 'Turcotte'],
		[first_name: 'Armand', last_name: 'Kshlerin'],
		[first_name: 'Albertha', last_name: 'Yundt'],
		[first_name: 'Kathryn', last_name: 'Mueller'],
		[first_name: 'Arely', last_name: 'McGlynn'],
		[first_name: 'Lawrence', last_name: 'Casper'],
		[first_name: 'Johathan', last_name: 'Kirlin'],
		[first_name: 'Clara', last_name: 'Gerhold'],
		[first_name: 'Miller', last_name: 'Feil'],
		[first_name: 'Rosendo', last_name: 'Sawayn'],
		[first_name: 'Sally', last_name: 'Mann'],
		[first_name: 'Kennith', last_name: 'Hettinger'],
		[first_name: 'Mathilde', last_name: 'Eichmann'],
		[first_name: 'AJ', last_name: 'Bhandal']
]

def productsData = new PrepareData().getProductData()

def ordersData = [
		[user_id: 41, product_id: 100, paid: true],
		[user_id: 27, product_id: 99, paid: false],
		[user_id: 50, product_id: 72, paid: false],
		[user_id: 24, product_id: 81, paid: true],
		[user_id: 24, product_id: 54, paid: true],
		[user_id: 1, product_id: 6, paid: true],
		[user_id: 17, product_id: 25, paid: false],
		[user_id: 8, product_id: 5, paid: true],
		[user_id: 34, product_id: 3, paid: true],
		[user_id: 41, product_id: 19, paid: true],
		[user_id: 15, product_id: 23, paid: true],
		[user_id: 23, product_id: 60, paid: true],
		[user_id: 31, product_id: 44, paid: true],
		[user_id: 46, product_id: 34, paid: false],
		[user_id: 11, product_id: 76, paid: false],
		[user_id: 44, product_id: 74, paid: true],
		[user_id: 18, product_id: 58, paid: true],
		[user_id: 40, product_id: 1, paid: false],
		[user_id: 41, product_id: 22, paid: true],
		[user_id: 10, product_id: 20, paid: false],
		[user_id: 50, product_id: 49, paid: false],
		[user_id: 14, product_id: 30, paid: true],
		[user_id: 4, product_id: 38, paid: false],
		[user_id: 42, product_id: 34, paid: true],
		[user_id: 22, product_id: 16, paid: false],
		[user_id: 4, product_id: 89, paid: true],
		[user_id: 49, product_id: 18, paid: true],
		[user_id: 35, product_id: 30, paid: true],
		[user_id: 7, product_id: 59, paid: false],
		[user_id: 31, product_id: 25, paid: true],
		[user_id: 43, product_id: 16, paid: false],
		[user_id: 18, product_id: 27, paid: false],
		[user_id: 47, product_id: 91, paid: true],
		[user_id: 32, product_id: 22, paid: false],
		[user_id: 5, product_id: 11, paid: false],
		[user_id: 14, product_id: 68, paid: false],
		[user_id: 19, product_id: 8, paid: false],
		[user_id: 43, product_id: 74, paid: true],
		[user_id: 29, product_id: 1, paid: false],
		[user_id: 7, product_id: 6, paid: true],
		[user_id: 16, product_id: 3, paid: true],
		[user_id: 29, product_id: 15, paid: false],
		[user_id: 25, product_id: 80, paid: true],
		[user_id: 5, product_id: 15, paid: true],
		[user_id: 23, product_id: 9, paid: true],
		[user_id: 20, product_id: 28, paid: false],
		[user_id: 18, product_id: 21, paid: true],
		[user_id: 34, product_id: 27, paid: false],
		[user_id: 33, product_id: 44, paid: true],
		[user_id: 26, product_id: 18, paid: false],
		[user_id: 10, product_id: 42, paid: false],
		[user_id: 49, product_id: 47, paid: true],
		[user_id: 4, product_id: 87, paid: true],
		[user_id: 8, product_id: 82, paid: true],
		[user_id: 32, product_id: 96, paid: true],
		[user_id: 3, product_id: 88, paid: true],
		[user_id: 2, product_id: 8, paid: true],
		[user_id: 49, product_id: 25, paid: false],
		[user_id: 3, product_id: 34, paid: true],
		[user_id: 38, product_id: 81, paid: false],
		[user_id: 41, product_id: 69, paid: true],
		[user_id: 50, product_id: 19, paid: true],
		[user_id: 44, product_id: 44, paid: false],
		[user_id: 20, product_id: 52, paid: false],
		[user_id: 16, product_id: 44, paid: false],
		[user_id: 50, product_id: 62, paid: false],
		[user_id: 47, product_id: 4, paid: false],
		[user_id: 4, product_id: 2, paid: true],
		[user_id: 36, product_id: 56, paid: true],
		[user_id: 49, product_id: 18, paid: true],
		[user_id: 20, product_id: 63, paid: true],
		[user_id: 18, product_id: 44, paid: true],
		[user_id: 30, product_id: 69, paid: true],
		[user_id: 33, product_id: 52, paid: true],
		[user_id: 18, product_id: 1, paid: true],
		[user_id: 39, product_id: 94, paid: true],
		[user_id: 39, product_id: 53, paid: true],
		[user_id: 31, product_id: 75, paid: true],
		[user_id: 39, product_id: 64, paid: false],
		[user_id: 33, product_id: 46, paid: false],
		[user_id: 16, product_id: 43, paid: false],
		[user_id: 41, product_id: 41, paid: false],
		[user_id: 33, product_id: 77, paid: true],
		[user_id: 8, product_id: 95, paid: false],
		[user_id: 16, product_id: 75, paid: false],
		[user_id: 4, product_id: 12, paid: false],
		[user_id: 14, product_id: 4, paid: true],
		[user_id: 31, product_id: 90, paid: true],
		[user_id: 30, product_id: 77, paid: true],
		[user_id: 44, product_id: 53, paid: false],
		[user_id: 34, product_id: 70, paid: true],
		[user_id: 23, product_id: 76, paid: false],
		[user_id: 22, product_id: 87, paid: false],
		[user_id: 45, product_id: 15, paid: true],
		[user_id: 14, product_id: 15, paid: true],
		[user_id: 6, product_id: 11, paid: true],
		[user_id: 3, product_id: 84, paid: false],
		[user_id: 25, product_id: 89, paid: true],
		[user_id: 5, product_id: 66, paid: true],
		[user_id: 40, product_id: 70, paid: false],
		[user_id: 10, product_id: 95, paid: true],
		[user_id: 22, product_id: 39, paid: true],
		[user_id: 13, product_id: 13, paid: false],
		[user_id: 12, product_id: 46, paid: false],
		[user_id: 28, product_id: 77, paid: false],
		[user_id: 14, product_id: 67, paid: false],
		[user_id: 11, product_id: 52, paid: false],
		[user_id: 11, product_id: 6, paid: false],
		[user_id: 32, product_id: 17, paid: true],
		[user_id: 40, product_id: 79, paid: true],
		[user_id: 5, product_id: 84, paid: true],
		[user_id: 38, product_id: 67, paid: false],
		[user_id: 45, product_id: 8, paid: false],
		[user_id: 21, product_id: 90, paid: true],
		[user_id: 38, product_id: 9, paid: true],
		[user_id: 23, product_id: 33, paid: false],
		[user_id: 14, product_id: 32, paid: false],
		[user_id: 47, product_id: 71, paid: false],
		[user_id: 15, product_id: 63, paid: true],
		[user_id: 12, product_id: 13, paid: true],
		[user_id: 32, product_id: 76, paid: true],
		[user_id: 17, product_id: 23, paid: true],
		[user_id: 48, product_id: 20, paid: false],
		[user_id: 25, product_id: 29, paid: true],
		[user_id: 20, product_id: 18, paid: true],
		[user_id: 49, product_id: 6, paid: true],
		[user_id: 28, product_id: 97, paid: false],
		[user_id: 2, product_id: 29, paid: true],
		[user_id: 36, product_id: 96, paid: false],
		[user_id: 13, product_id: 99, paid: false],
		[user_id: 36, product_id: 70, paid: false],
		[user_id: 34, product_id: 38, paid: true],
		[user_id: 15, product_id: 11, paid: false],
		[user_id: 19, product_id: 17, paid: false],
		[user_id: 32, product_id: 73, paid: true],
		[user_id: 45, product_id: 27, paid: true],
		[user_id: 34, product_id: 86, paid: false],
		[user_id: 27, product_id: 68, paid: true],
		[user_id: 49, product_id: 90, paid: false],
		[user_id: 10, product_id: 60, paid: true],
		[user_id: 31, product_id: 84, paid: false],
		[user_id: 35, product_id: 83, paid: false],
		[user_id: 28, product_id: 43, paid: false],
		[user_id: 39, product_id: 95, paid: false],
		[user_id: 11, product_id: 53, paid: true],
		[user_id: 8, product_id: 89, paid: true],
		[user_id: 23, product_id: 7, paid: true],
		[user_id: 39, product_id: 42, paid: false],
		[user_id: 41, product_id: 60, paid: false],
		[user_id: 25, product_id: 18, paid: true],
		[user_id: 38, product_id: 88, paid: false],
		[user_id: 47, product_id: 69, paid: true],
		[user_id: 15, product_id: 13, paid: true],
		[user_id: 37, product_id: 35, paid: false],
		[user_id: 37, product_id: 52, paid: true],
		[user_id: 12, product_id: 80, paid: false],
		[user_id: 39, product_id: 40, paid: true],
		[user_id: 28, product_id: 23, paid: false],
		[user_id: 3, product_id: 58, paid: false],
		[user_id: 33, product_id: 92, paid: false],
		[user_id: 38, product_id: 51, paid: true],
		[user_id: 18, product_id: 15, paid: false],
		[user_id: 25, product_id: 57, paid: false],
		[user_id: 46, product_id: 28, paid: false],
		[user_id: 42, product_id: 49, paid: true],
		[user_id: 31, product_id: 5, paid: true],
		[user_id: 37, product_id: 29, paid: false],
		[user_id: 4, product_id: 64, paid: true],
		[user_id: 23, product_id: 12, paid: false],
		[user_id: 37, product_id: 93, paid: true],
		[user_id: 13, product_id: 46, paid: true],
		[user_id: 4, product_id: 95, paid: false],
		[user_id: 44, product_id: 59, paid: true],
		[user_id: 39, product_id: 72, paid: false],
		[user_id: 28, product_id: 44, paid: true],
		[user_id: 3, product_id: 55, paid: false],
		[user_id: 17, product_id: 36, paid: false],
		[user_id: 7, product_id: 40, paid: false],
		[user_id: 4, product_id: 69, paid: true],
		[user_id: 39, product_id: 22, paid: true],
		[user_id: 25, product_id: 2, paid: false],
		[user_id: 21, product_id: 88, paid: false],
		[user_id: 13, product_id: 1, paid: true],
		[user_id: 34, product_id: 76, paid: false],
		[user_id: 9, product_id: 19, paid: true],
		[user_id: 43, product_id: 95, paid: false],
		[user_id: 42, product_id: 16, paid: false],
		[user_id: 50, product_id: 35, paid: false],
		[user_id: 7, product_id: 61, paid: false],
		[user_id: 16, product_id: 17, paid: true],
		[user_id: 45, product_id: 25, paid: true],
		[user_id: 36, product_id: 53, paid: true],
		[user_id: 5, product_id: 85, paid: false],
		[user_id: 1, product_id: 27, paid: true],
		[user_id: 29, product_id: 29, paid: true],
		[user_id: 14, product_id: 41, paid: true],
		[user_id: 1, product_id: 95, paid: true],
		[user_id: 2, product_id: 1, paid: true],
		[user_id: 43, product_id: 63, paid: true],
		[user_id: 6, product_id: 36, paid: true],
		[user_id: 34, product_id: 26, paid: true],
		[user_id: 35, product_id: 52, paid: false],
		[user_id: 14, product_id: 92, paid: true],
		[user_id: 18, product_id: 100, paid: true],
		[user_id: 13, product_id: 17, paid: true],
		[user_id: 25, product_id: 69, paid: false],
		[user_id: 45, product_id: 3, paid: false],
		[user_id: 37, product_id: 85, paid: false],
		[user_id: 44, product_id: 87, paid: false],
		[user_id: 36, product_id: 1, paid: true],
		[user_id: 15, product_id: 68, paid: false],
		[user_id: 12, product_id: 30, paid: true],
		[user_id: 22, product_id: 41, paid: false],
		[user_id: 16, product_id: 26, paid: true],
		[user_id: 34, product_id: 46, paid: false],
		[user_id: 33, product_id: 33, paid: false],
		[user_id: 31, product_id: 31, paid: false],
		[user_id: 41, product_id: 75, paid: true],
		[user_id: 32, product_id: 66, paid: false],
		[user_id: 11, product_id: 30, paid: true],
		[user_id: 29, product_id: 20, paid: false],
		[user_id: 16, product_id: 13, paid: false],
		[user_id: 39, product_id: 79, paid: false],
		[user_id: 45, product_id: 94, paid: false],
		[user_id: 9, product_id: 96, paid: false],
		[user_id: 36, product_id: 47, paid: false],
		[user_id: 2, product_id: 34, paid: true],
		[user_id: 43, product_id: 38, paid: true],
		[user_id: 27, product_id: 6, paid: true],
		[user_id: 19, product_id: 55, paid: true],
		[user_id: 29, product_id: 48, paid: false],
		[user_id: 45, product_id: 85, paid: false],
		[user_id: 18, product_id: 38, paid: false],
		[user_id: 1, product_id: 15, paid: true],
		[user_id: 13, product_id: 25, paid: false],
		[user_id: 14, product_id: 10, paid: false],
		[user_id: 31, product_id: 28, paid: false],
		[user_id: 20, product_id: 85, paid: false],
		[user_id: 18, product_id: 88, paid: true],
		[user_id: 8, product_id: 8, paid: false],
		[user_id: 24, product_id: 58, paid: false],
		[user_id: 24, product_id: 48, paid: true],
		[user_id: 24, product_id: 68, paid: false],
		[user_id: 29, product_id: 87, paid: true],
		[user_id: 6, product_id: 36, paid: true],
		[user_id: 46, product_id: 51, paid: true],
		[user_id: 20, product_id: 21, paid: false],
		[user_id: 18, product_id: 40, paid: true],
		[user_id: 36, product_id: 12, paid: false],
		[user_id: 22, product_id: 54, paid: true],
		[user_id: 22, product_id: 10, paid: true],
		[user_id: 20, product_id: 13, paid: false],
		[user_id: 2, product_id: 33, paid: true],
		[user_id: 20, product_id: 46, paid: true],
		[user_id: 48, product_id: 37, paid: true],
		[user_id: 41, product_id: 2, paid: false],
		[user_id: 2, product_id: 53, paid: true],
		[user_id: 45, product_id: 87, paid: false],
		[user_id: 5, product_id: 35, paid: false],
		[user_id: 28, product_id: 46, paid: false],
		[user_id: 42, product_id: 79, paid: true],
		[user_id: 27, product_id: 45, paid: false],
		[user_id: 11, product_id: 21, paid: false],
		[user_id: 36, product_id: 96, paid: false],
		[user_id: 35, product_id: 59, paid: true],
		[user_id: 30, product_id: 92, paid: true],
		[user_id: 17, product_id: 28, paid: false],
		[user_id: 28, product_id: 28, paid: true],
		[user_id: 23, product_id: 43, paid: true],
		[user_id: 44, product_id: 24, paid: false],
		[user_id: 26, product_id: 98, paid: false],
		[user_id: 36, product_id: 51, paid: false],
		[user_id: 1, product_id: 66, paid: false],
		[user_id: 47, product_id: 92, paid: false],
		[user_id: 1, product_id: 36, paid: false],
		[user_id: 9, product_id: 8, paid: false],
		[user_id: 42, product_id: 97, paid: true],
		[user_id: 32, product_id: 38, paid: false],
		[user_id: 17, product_id: 60, paid: true],
		[user_id: 14, product_id: 24, paid: true],
		[user_id: 43, product_id: 14, paid: true],
		[user_id: 47, product_id: 21, paid: true],
		[user_id: 38, product_id: 46, paid: true],
		[user_id: 22, product_id: 75, paid: false],
		[user_id: 19, product_id: 47, paid: true],
		[user_id: 10, product_id: 37, paid: true],
		[user_id: 9, product_id: 11, paid: true],
		[user_id: 44, product_id: 56, paid: true],
		[user_id: 50, product_id: 6, paid: true],
		[user_id: 21, product_id: 99, paid: false],
		[user_id: 34, product_id: 4, paid: true],
		[user_id: 5, product_id: 37, paid: false],
		[user_id: 8, product_id: 11, paid: false],
		[user_id: 12, product_id: 66, paid: false],
		[user_id: 21, product_id: 74, paid: true],
		[user_id: 38, product_id: 53, paid: false],
		[user_id: 24, product_id: 54, paid: false],
		[user_id: 33, product_id: 85, paid: true],
		[user_id: 9, product_id: 57, paid: false],
		[user_id: 20, product_id: 71, paid: true],
		[user_id: 21, product_id: 4, paid: false],
		[user_id: 38, product_id: 96, paid: false],
		[user_id: 35, product_id: 50, paid: false],
		[user_id: 16, product_id: 89, paid: false],
		[user_id: 45, product_id: 95, paid: true],
		[user_id: 33, product_id: 92, paid: false],
		[user_id: 41, product_id: 87, paid: false],
		[user_id: 25, product_id: 15, paid: false],
		[user_id: 42, product_id: 86, paid: false],
		[user_id: 2, product_id: 68, paid: false],
		[user_id: 5, product_id: 85, paid: true],
		[user_id: 42, product_id: 43, paid: false],
		[user_id: 15, product_id: 8, paid: true],
		[user_id: 13, product_id: 3, paid: true],
		[user_id: 24, product_id: 86, paid: false],
		[user_id: 34, product_id: 66, paid: false],
		[user_id: 35, product_id: 98, paid: false],
		[user_id: 48, product_id: 90, paid: false],
		[user_id: 34, product_id: 97, paid: false],
		[user_id: 48, product_id: 36, paid: true],
		[user_id: 21, product_id: 31, paid: false],
		[user_id: 40, product_id: 93, paid: false],
		[user_id: 26, product_id: 89, paid: true],
		[user_id: 47, product_id: 15, paid: true],
		[user_id: 27, product_id: 24, paid: true],
		[user_id: 30, product_id: 34, paid: false],
		[user_id: 44, product_id: 23, paid: true],
		[user_id: 17, product_id: 54, paid: true],
		[user_id: 31, product_id: 42, paid: false],
		[user_id: 42, product_id: 32, paid: false],
		[user_id: 20, product_id: 55, paid: true],
		[user_id: 2, product_id: 80, paid: true],
		[user_id: 30, product_id: 70, paid: true],
		[user_id: 24, product_id: 18, paid: true],
		[user_id: 5, product_id: 96, paid: false],
		[user_id: 50, product_id: 31, paid: false],
		[user_id: 35, product_id: 98, paid: true],
		[user_id: 41, product_id: 30, paid: false],
		[user_id: 48, product_id: 22, paid: true],
		[user_id: 19, product_id: 31, paid: false],
		[user_id: 34, product_id: 33, paid: false],
		[user_id: 19, product_id: 58, paid: false],
		[user_id: 26, product_id: 72, paid: false],
		[user_id: 34, product_id: 59, paid: true],
		[user_id: 8, product_id: 39, paid: true],
		[user_id: 40, product_id: 73, paid: false],
		[user_id: 44, product_id: 56, paid: false],
		[user_id: 36, product_id: 91, paid: true],
		[user_id: 33, product_id: 56, paid: false],
		[user_id: 36, product_id: 90, paid: true],
		[user_id: 28, product_id: 22, paid: false],
		[user_id: 49, product_id: 70, paid: true],
		[user_id: 19, product_id: 14, paid: true],
		[user_id: 39, product_id: 59, paid: false],
		[user_id: 17, product_id: 39, paid: false],
		[user_id: 40, product_id: 72, paid: true],
		[user_id: 21, product_id: 96, paid: false],
		[user_id: 3, product_id: 66, paid: true],
		[user_id: 23, product_id: 6, paid: true],
		[user_id: 6, product_id: 6, paid: false],
		[user_id: 18, product_id: 52, paid: true],
		[user_id: 48, product_id: 87, paid: true],
		[user_id: 40, product_id: 83, paid: true],
		[user_id: 23, product_id: 10, paid: true],
		[user_id: 21, product_id: 6, paid: false],
		[user_id: 24, product_id: 63, paid: true],
		[user_id: 18, product_id: 67, paid: false],
		[user_id: 35, product_id: 47, paid: false],
		[user_id: 26, product_id: 62, paid: false],
		[user_id: 14, product_id: 37, paid: false],
		[user_id: 9, product_id: 51, paid: false],
		[user_id: 1, product_id: 51, paid: true],
		[user_id: 35, product_id: 29, paid: false],
		[user_id: 49, product_id: 66, paid: true],
		[user_id: 45, product_id: 47, paid: false],
		[user_id: 26, product_id: 52, paid: false],
		[user_id: 31, product_id: 60, paid: false],
		[user_id: 4, product_id: 89, paid: false],
		[user_id: 43, product_id: 46, paid: true],
		[user_id: 16, product_id: 23, paid: false],
		[user_id: 37, product_id: 97, paid: true],
		[user_id: 47, product_id: 70, paid: false],
		[user_id: 22, product_id: 88, paid: false],
		[user_id: 21, product_id: 45, paid: true],
		[user_id: 46, product_id: 25, paid: true],
		[user_id: 36, product_id: 80, paid: true],
		[user_id: 42, product_id: 20, paid: true],
		[user_id: 14, product_id: 5, paid: false],
		[user_id: 10, product_id: 65, paid: false],
		[user_id: 14, product_id: 30, paid: false],
		[user_id: 1, product_id: 37, paid: false],
		[user_id: 2, product_id: 22, paid: true],
		[user_id: 41, product_id: 3, paid: true],
		[user_id: 47, product_id: 17, paid: true],
		[user_id: 34, product_id: 50, paid: true],
		[user_id: 23, product_id: 60, paid: false],
		[user_id: 13, product_id: 29, paid: true],
		[user_id: 18, product_id: 16, paid: true],
		[user_id: 23, product_id: 91, paid: true],
		[user_id: 46, product_id: 68, paid: false],
		[user_id: 3, product_id: 87, paid: false],
		[user_id: 31, product_id: 52, paid: false],
		[user_id: 49, product_id: 23, paid: false],
		[user_id: 50, product_id: 75, paid: true],
		[user_id: 20, product_id: 43, paid: true],
		[user_id: 13, product_id: 100, paid: false],
		[user_id: 14, product_id: 6, paid: false],
		[user_id: 19, product_id: 99, paid: true],
		[user_id: 45, product_id: 82, paid: true],
		[user_id: 41, product_id: 66, paid: true],
		[user_id: 9, product_id: 39, paid: true],
		[user_id: 18, product_id: 41, paid: true],
		[user_id: 47, product_id: 17, paid: false],
		[user_id: 25, product_id: 100, paid: true],
		[user_id: 49, product_id: 57, paid: false],
		[user_id: 41, product_id: 15, paid: false],
		[user_id: 22, product_id: 41, paid: false],
		[user_id: 15, product_id: 1, paid: true],
		[user_id: 29, product_id: 96, paid: true],
		[user_id: 2, product_id: 78, paid: true],
		[user_id: 4, product_id: 87, paid: true],
		[user_id: 22, product_id: 99, paid: true],
		[user_id: 41, product_id: 7, paid: false],
		[user_id: 6, product_id: 98, paid: true],
		[user_id: 41, product_id: 20, paid: false],
		[user_id: 25, product_id: 17, paid: false],
		[user_id: 21, product_id: 54, paid: true],
		[user_id: 48, product_id: 64, paid: true],
		[user_id: 4, product_id: 29, paid: false],
		[user_id: 46, product_id: 98, paid: true],
		[user_id: 23, product_id: 66, paid: true],
		[user_id: 35, product_id: 64, paid: true],
		[user_id: 37, product_id: 98, paid: false],
		[user_id: 30, product_id: 84, paid: false],
		[user_id: 8, product_id: 24, paid: false],
		[user_id: 12, product_id: 56, paid: true],
		[user_id: 7, product_id: 23, paid: true],
		[user_id: 25, product_id: 31, paid: true],
		[user_id: 25, product_id: 46, paid: false],
		[user_id: 49, product_id: 80, paid: false],
		[user_id: 29, product_id: 97, paid: false],
		[user_id: 30, product_id: 60, paid: true],
		[user_id: 50, product_id: 37, paid: true],
		[user_id: 42, product_id: 48, paid: false],
		[user_id: 44, product_id: 24, paid: true],
		[user_id: 34, product_id: 93, paid: true],
		[user_id: 7, product_id: 44, paid: true],
		[user_id: 34, product_id: 13, paid: true],
		[user_id: 37, product_id: 47, paid: false],
		[user_id: 40, product_id: 12, paid: false],
		[user_id: 43, product_id: 76, paid: true],
		[user_id: 41, product_id: 2, paid: false],
		[user_id: 12, product_id: 22, paid: true],
		[user_id: 2, product_id: 75, paid: true],
		[user_id: 19, product_id: 18, paid: false],
		[user_id: 31, product_id: 39, paid: true],
		[user_id: 20, product_id: 72, paid: true],
		[user_id: 25, product_id: 15, paid: false],
		[user_id: 42, product_id: 34, paid: false],
		[user_id: 33, product_id: 13, paid: false],
		[user_id: 40, product_id: 8, paid: true],
		[user_id: 5, product_id: 33, paid: true],
		[user_id: 44, product_id: 28, paid: true],
		[user_id: 29, product_id: 5, paid: true],
		[user_id: 37, product_id: 88, paid: false],
		[user_id: 44, product_id: 61, paid: false],
		[user_id: 1, product_id: 57, paid: false],
		[user_id: 39, product_id: 28, paid: true],
		[user_id: 25, product_id: 88, paid: false],
		[user_id: 47, product_id: 52, paid: false],
		[user_id: 1, product_id: 42, paid: false],
		[user_id: 26, product_id: 97, paid: true],
		[user_id: 29, product_id: 24, paid: false],
		[user_id: 19, product_id: 48, paid: true],
		[user_id: 5, product_id: 60, paid: true],
		[user_id: 45, product_id: 74, paid: true],
		[user_id: 25, product_id: 97, paid: true],
		[user_id: 37, product_id: 71, paid: false],
		[user_id: 30, product_id: 18, paid: false],
		[user_id: 7, product_id: 6, paid: true],
		[user_id: 38, product_id: 9, paid: true],
		[user_id: 36, product_id: 56, paid: true],
		[user_id: 34, product_id: 17, paid: true],
		[user_id: 19, product_id: 90, paid: true],
		[user_id: 7, product_id: 16, paid: true],
		[user_id: 6, product_id: 43, paid: true],
		[user_id: 15, product_id: 22, paid: false],
		[user_id: 1, product_id: 60, paid: true],
		[user_id: 9, product_id: 65, paid: true],
		[user_id: 35, product_id: 21, paid: true],
		[user_id: 18, product_id: 62, paid: false],
		[user_id: 1, product_id: 36, paid: false],
		[user_id: 30, product_id: 26, paid: false],
		[user_id: 12, product_id: 82, paid: false],
		[user_id: 34, product_id: 30, paid: false],
		[user_id: 18, product_id: 86, paid: true],
		[user_id: 12, product_id: 77, paid: true],
		[user_id: 12, product_id: 37, paid: false],
		[user_id: 31, product_id: 12, paid: false],
		[user_id: 6, product_id: 28, paid: false],
		[user_id: 13, product_id: 68, paid: false],
		[user_id: 41, product_id: 81, paid: true],
		[user_id: 6, product_id: 87, paid: false],
		[user_id: 21, product_id: 10, paid: false],
		[user_id: 28, product_id: 53, paid: true],
		[user_id: 30, product_id: 22, paid: false],
		[user_id: 47, product_id: 24, paid: false],
		[user_id: 22, product_id: 84, paid: false],
		[user_id: 21, product_id: 88, paid: false],
		[user_id: 39, product_id: 81, paid: true],
		[user_id: 42, product_id: 15, paid: false],
		[user_id: 25, product_id: 31, paid: true],
		[user_id: 1, product_id: 6, paid: false],
		[user_id: 11, product_id: 82, paid: true],
		[user_id: 8, product_id: 64, paid: false],
		[user_id: 50, product_id: 16, paid: true],
		[user_id: 17, product_id: 9, paid: false],
		[user_id: 41, product_id: 36, paid: true],
		[user_id: 23, product_id: 18, paid: true],
		[user_id: 32, product_id: 64, paid: true],
		[user_id: 2, product_id: 73, paid: true],
		[user_id: 24, product_id: 52, paid: true],
		[user_id: 22, product_id: 12, paid: true],
		[user_id: 17, product_id: 32, paid: true],
		[user_id: 32, product_id: 76, paid: true],
		[user_id: 20, product_id: 95, paid: false],
		[user_id: 36, product_id: 33, paid: true],
		[user_id: 18, product_id: 52, paid: false],
		[user_id: 24, product_id: 34, paid: true],
		[user_id: 21, product_id: 48, paid: false],
		[user_id: 9, product_id: 65, paid: false],
		[user_id: 7, product_id: 67, paid: true],
		[user_id: 22, product_id: 54, paid: false],
		[user_id: 18, product_id: 40, paid: false],
		[user_id: 6, product_id: 11, paid: true],
		[user_id: 29, product_id: 34, paid: true],
		[user_id: 39, product_id: 11, paid: true],
		[user_id: 16, product_id: 60, paid: false],
		[user_id: 19, product_id: 11, paid: false],
		[user_id: 31, product_id: 38, paid: false],
		[user_id: 18, product_id: 58, paid: true],
		[user_id: 7, product_id: 16, paid: false],
		[user_id: 12, product_id: 85, paid: false],
		[user_id: 32, product_id: 95, paid: false],
		[user_id: 24, product_id: 45, paid: false],
		[user_id: 50, product_id: 80, paid: false],
		[user_id: 5, product_id: 66, paid: true],
		[user_id: 27, product_id: 56, paid: false],
		[user_id: 36, product_id: 95, paid: false],
		[user_id: 3, product_id: 32, paid: true]
]

productsData.forEach {
	sql.executeInsert("""
INSERT INTO products(name, department, price, weight) values (${it.name}, ${it.department}, ${Double.parseDouble(it.price)}, ${Double.parseDouble(it.weight)})
""")
}

usersData.forEach {
	sql.executeInsert("""
		INSERT INTO users (first_name, last_name) values (${it.first_name}, ${it.last_name})
	""")
}

ordersData.forEach {
	sql.executeInsert("""
	INSERT INTO orders (user_id, product_id, paid) values (${it.user_id}, ${it.product_id}, ${it.paid})
""")
}







